version: "3.9"

services:
  # Database for Core service
  db-core:
    image: postgres:15-alpine
    container_name: db-core
    environment:
      POSTGRES_USER: core_user
      POSTGRES_PASSWORD: core_pass
      POSTGRES_DB: core_db
    volumes:
      - core_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
  # Core Microservice (Django)
  core-service:
    build: .
    container_name: core-service
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:  # only for working in Dev-mode, remove in production
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db-core
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8000/api/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
volumes:
  core_db_data:

